title: "CodeLee's Website"
description: "Every person deserves to feel safe, calm, loved。"
author: "CodeLee"
email: "448467580@qq.com"

url: "https://knowno.github.io"
baseurl: ""

theme: minima
show_excerpts: false
paginate: 5
paginate_path: "/page:num/"

github_username: knowno

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

footer:
  copyright: "© 2025 CodeLee. All rights reserved."
